### ISSUE TITLE
Jrfs critique request 

### ISSUE THREAD

**Issue by waynesbrain** [mbrt/blog#2]
Hello. I saw your post about GlassDB on Hacker News today. I think you are probably a much more educated programmer than I am, so I was wondering if you would give a critique or any feedback of my work at https://github.com/jrfso/jrfs

It’s a database-like file access system. I also could not find anything nearly similar to what I built there and it’s tangentially similar to what you have done.

If not, no biggie! Thanks for your article and sorry if this issue is the wrong way to contact you.

**Comment by mbrt** [comment]
Hi! I read through the README, and it's not clear to me what is the main purpose. I see many features, but they seem all slightly unrelated to each other. This is just from a superficial read, but I would recommend to:

* Do only one thing, and well. If there's space for more features, without bloating the project, they will come naturally from a well-designed base.
* Exposing unrestricted server side operations to client is problematic from a security perspective, but it seems you're just targeting the local machine?
* What is the main value proposition? You mention that it's for `tools that need more than the standard browser File System API but less than a full-blown Electron/Chromium installation`. I wonder what's wrong with having a full-blown installation. Perhaps you could elaborate on that?

**Comment by mbrt** [comment]
Gotcha. I can see how this can be useful, however it doesn't seem to relate to what I'm doing with [glassdb](https://github.com/mbrt/glassdb)? It's a key value store on top of object storage, there's no frontend or local file system involved, so it is quite a different goal.

**Comment by mbrt** [comment]
No worries! Sorry, I'm not an expert in what you're doing, so I can't really help. In any case, keep on building and sharing! That's the best way to create useful things (and learn).
